### ISSUE TITLE
make database connection parameter as implicit

### ISSUE THREAD

**Issue by skyhills13** [skyhills13/jaguar-scala#34]

**Comment by skyhills13** [comment]
![screen shot 2018-10-21 at 9 54 34 pm](https://user-images.githubusercontent.com/3893707/47267218-e9806680-d57b-11e8-9ebb-71e5223c7a34.png)
15라인의 Database transactor를 없애려고 했던것인데 constructor argument라 불가능함

**Comment by Kevin-Lee** [comment]
You can have that `Database.transactor()` in the repository `object`, but is it good to have it like that?
