### ISSUE TITLE
Change *Repository classes to object 

### ISSUE THREAD

**Issue by skyhills13** [skyhills13/jaguar-scala#36]
They doesn't need to be able to create multiple instances.

**Comment by skyhills13** [comment]
하지만 과연 이것이 옳은 선택인가
https://github.com/skyhills13/jaguar-scala/issues/34
이걸 치려다가 발견한 이슈임

**Comment by Kevin-Lee** [comment]
You already found an issue. So considering that does it really worth making it object?
Please also think about my comment [there](34#issuecomment-431685115).

**Comment by Kevin-Lee** [comment]
Having `object` and DB connection hard-coded, is it easy to test?

**Comment by skyhills13** [comment]
Nope. Definitely not. And object would have another problem if there are multiple datasource.
Hm. I got it!

**Comment by skyhills13** [comment]
DB is external resource which is not good to hard code
